### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by weakfl** [Supmenow/fastlane-plugin-poeditor-export#3]
Could you please publish version 0.3.0 on RubyGems.org?
I'd really love to use the tag support introduced in version 0.3.0.

**Comment by jcampbell05** [comment]
Sure :) I'll push it out tommorow

**Comment by weakfl** [comment]
Nice, thanks! Very useful plugin btw...

**Comment by jcampbell05** [comment]
Cheers :) It's released now.
