### ISSUE TITLE
Not translated strings

### ISSUE THREAD

**Issue by mgursch** [Supmenow/fastlane-plugin-poeditor-export#5]
Hello

when i am exporting my strings from poeditor via your fastlane action, I get a lot of empty strings because of not translated values.
<string name="asdf"></string>

How can I disable exporting of these not translated strings?

**Comment by SpacyRicochet** [comment]
Hello @mgursch,

This tool uses the basic POEditor export functionality, but that export always exports empty strings for non-translated values, without an option to disable this.

However, there is a project setting where you can select another language for untranslated strings, to be used _instead_ of the empty string.

<img width="624" alt="Screenshot 2019-05-22 at 13 48 08" src="https://user-images.githubusercontent.com/904596/58172239-3f46f980-7c98-11e9-9a1e-007a31b98883.png">

An option to not include untranslated values, or to export them as their keys, was requested, but it's obviously not a priority for the POEditor team. But you're welcome to [poke them](https://poeditor.com/contact/) 😁

 I hope that helps!
